/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 10 09:45:46 GMT 2025
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Demo_ESTest extends Demo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Demo demo0 = new Demo();
      int int0 = demo0.subtract((-908), (-908));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Demo demo0 = new Demo();
      int int0 = demo0.subtract(0, (-590));
      assertEquals(590, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Demo demo0 = new Demo();
      int int0 = demo0.add(1372, 0);
      assertEquals(1372, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Demo demo0 = new Demo();
      int int0 = demo0.add(0, (-2449));
      assertEquals((-2449), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Demo demo0 = new Demo();
      int int0 = demo0.subtract(0, 908);
      assertEquals((-908), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Demo demo0 = new Demo();
      int int0 = demo0.add(0, 0);
      assertEquals(0, int0);
  }
}
